<!-- BEGIN Money generated by this client in this year -->
<div class="col-md-6">

    <!-- BEGIN Custom well -->
    <div class="well custom-well grey-text">

        <!-- BEGIN Money generated by this client in this year title -->
        <div>
            <strong>
                {{ trans('clients.money_generated_by_this_client_in_this_year') }}: @{{ client.statistics.earnings_in_current_year }} ron
            </strong>
        </div>
        <!-- END Money generated by this client in this year title -->

        <!-- BEGIN Money generated by this client more details -->
        <div>
            <span class="more-details">@{{ client.money_generated_in_current_year }}</span>
        </div>
        <!-- END Money generated by this client more details -->

    </div>
    <!-- END Custom well -->

</div>
<!-- END Money generated by this client in this year -->