<!-- BEGIN Money generated by this client -->
<div class="col-md-6">
    <div class="well custom-well grey-text">
        <div><strong>{{ trans('clients.money_generated_by_this_client') }}</strong></div>
        <div>Acest client a efectuata vanzari de 123 ron in total.</div>
    </div>
</div>
<!-- END Money generated by this client -->